# permissions for end users to view groupconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupconfig-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - groupconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - groupconfigs/status
  verbs:
  - get
