# permissions for end users to edit groupconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupconfig-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - groupconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - groupconfigs/status
  verbs:
  - get
