# permissions for end users to view namespaceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceconfig-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaceconfigs/status
  verbs:
  - get
