# permissions for end users to view userconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: userconfig-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - userconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - userconfigs/status
  verbs:
  - get
