apiVersion: redhatcop.redhat.io/v1alpha1
kind: UserConfig
metadata:
  name: user-sandbox
spec:
  providerName: my-provider
  templates:
  - objectTemplate: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ .Name }}-sandbox
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{ .Name }}-sandbox
        namespace: {{ .Name }}-sandbox
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }}      
  - objectTemplate: | 
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: standard-sandbox
        namespace: {{ .Name }}-sandbox
      spec:
        hard:
          pods: "4" 
          requests.cpu: "1" 
          requests.memory: 1Gi 
          requests.ephemeral-storage: 2Gi 
          limits.cpu: "2" 
          limits.memory: 2Gi 
          limits.ephemeral-storage: 4Gi
  - objectTemplate: |
      kind: EgressNetworkPolicy
      apiVersion: network.openshift.io/v1
      metadata:
        name: air-gapped-sandbox
        namespace: {{ .Name }}-sandbox
      spec:
        egress:
        - type: Deny
          to:
            cidrSelector: 10.20.0.0/0
  - objectTemplate: |          
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-from-same-namespace
        namespace: {{ .Name }}-sandbox
      spec:
        podSelector:
        ingress:
        - from:
          - podSelector: {}
        policyTypes:
          - Ingress   
  - objectTemplate: |      
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-from-openshift-ingress
        namespace: {{ .Name }}-sandbox
      spec:
        ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                network.openshift.io/policy-group: ingress
        podSelector: {}
        policyTypes:
        - Ingress                    